### ISSUE TITLE
alternative ;)

### ISSUE THREAD

**Issue by vitaly-t** [jacoscaz/node-pg-sidekick#1]
just in case you missed [pg-promise], which already does all that ;)

[pg-promise]:https://github.com/vitaly-t/pg-promise

**Comment by jacoscaz** [comment]
Hello @vitaly-t! Thank you for your suggestion.

I wrote `pg-sidekick` mainly because I needed a very simple wrapper to integrate w/ the `squel.js` query builder module and because I often like to replicate bits of functionality I find myself using a lot but never actually implemented on my own. The process always teaches me something, even though sometimes the results are not worth keeping around. I've done a similar thing while writing `brooklet`, which taught me a lot about streams, even though Caolan's `highlandjs` module - the main source of inspiration in that particular case - is spectacularly more advanced and production-worthy.

This said, I actually use `pg-promise` in a couple of projects and really like it. For production purposes, I believe it is a much better choice than `pg-sidekick`. I'll  update `README.md` to reflect this.

**Comment by jacoscaz** [comment]
Closed by ca4b572.
